DROP TABLE TM_EmployeeTeam;
DROP TABLE TM_ProjectERTemplate;
DROP TABLE Employee;
DROP TABLE ExpenseLine;
DROP TABLE ExpenseReport;
DROP TABLE PaymentType;
DROP TABLE Project;
DROP TABLE ExpenseType;
DROP TABLE ExpenseCurrency;
DROP TABLE Assignment;
DROP TABLE AppUser;
DROP TABLE AdminUser;
DROP TABLE OperatorUser;
DROP TABLE Team;
DROP TABLE ERTemplate;
DROP TABLE ERLTemplate;
DROP TABLE ExchangeHistory;
DROP TABLE SystemParam;

DROP TABLE GridPreferences
